### ISSUE TITLE
resource generateCloudInit deployed failed.

### ISSUE THREAD

**Issue by pospospos2007** [kartben/thethingsstack-on-azure#4]
I clicked the azure button you mentioned in doc.  only resource called "generateCloudInit" deployed failed.
I got this error :
 
 
{
    "status": "failed",
    "error": {
        "code": "DeploymentScriptACIProvisioningTimeout",
        "message": "The supporting resource: 'Azure Container Instance' did not provision during the expected time. Correlation Id: 41c19c12-b125-4734-8351-4a58abd54224. Please try again later, if the issue persists contact technical support for further investigation."
    }
}

do you know what is this issue? Thank you!

**Comment by pospospos2007** [comment]
Here are more details
{
    "status": "failed",
    "error": {
        "code": "DeploymentScriptOperationFailed",
        "message": "Object reference not set to an instance of an object."
    }
}


![image](https://user-images.githubusercontent.com/11675650/127356695-5d02dbbd-c679-4876-860a-3678cdd5d83c.png)

**Comment by mdredmond** [comment]
I have exactly the same problem.  I'm disappointed.

It took me 15 minutes to get ChirpStack up and running but The Things Stack on Azure has been killing me for days.

**Comment by kartben** [comment]
Hi both -- there seems to be an issue indeed. I am currently investigating and hope to be able to fix this shortly! Thanks for your patience :)

**Comment by mdredmond** [comment]
Awesome if you find the problem.  I appreciate your efforts because if it works, this is very, very cool!

Nice article in Make, by the way!

**Comment by kartben** [comment]
Hi @mdredmond  and @pospospos2007 -- I have some good news for you both, the issue you kindly reported is now fixed, and I've also used the opportunity to upgrade the ARM template to the latest version of The Things Stack ( v3.14.1) 🎆 For the anecdote, the culprit was an emoji in the default name that I was giving to the Things Stack instance, that was causing a container to fail to deploy 😢. Note that since v3.11+ of The Things Stack now includes support for the Device Repository, the deployment takes a bit longer (I have updated the README file accordingly) as the initial indexing of the repo is a long-running operation.

Please do let me know if this works fine for you now, and do not hesitate to report other issues in the future.

**Comment by mdredmond** [comment]
Oh my!  I almost removed that emoji!  The little rocket ship.  I should have.

Thanks for looking into it!

**Comment by kartben** [comment]
> Oh my! I almost removed that emoji! The little rocket ship. I should have.

Ya, I know! Interestingly, it used to work just fine with that emoji, so that's why it took me extra long time to figure out the issue, as I couldn't find anything obvious that would have caused the ARM template to suddenly get stuck when deploying the container needed for the "custom deployment script".
